mqtt_client:
  ros__parameters:
    broker:
      host: "10.0.1.137"
      port: 1883
      tls:
        enabled: false
    client:
      id: "rt1_mqtt_client"
      clean_session: true
      keep_alive_interval: 60.0
      max_inflight: 65535
    bridge:
      ros2mqtt:
        ros_topics: 
          - "/rosrt_rt1"
        "/rosrt_rt1":
          mqtt_topic: "/rt1"
          ros_type: "rosrt_rt1/msg/Rt1Sensor"
          inject_timestamp: true
          advanced:
            ros:
              queue_size: 10
            mqtt:
              qos: 1