/**:
  ros__parameters:
    # Launch configuration
    launch_config:
      use_sim: false
      use_rviz: false
      use_slam: true
      use_nav2: true
      mode: "teleop"  # "sensor" or "teleop"
      
    # Hardware configuration
    hardware:
      real_robot:
        port: "/dev/rt1"
        baud_rate: 115200
        timeout_ms: 1000
      
      lidar:
        auto_start: "true"
        node_name: "rt1_urg_node2"
        serial_port: "/dev/hokuyo"
        serial_baud: 115200
        frame_id: "hokuyo_link"
        scan_topic_name: "scan"
        angle_min: -3.14
        angle_max: 3.14

      odometry:
        publish_rate: 100.0
        base_frame: "base_link"
        odom_frame: "odom"
        use_tf: true
    
    # Robot parameters
    robot:
      base_frame: "base_link"
      wheel_separation: 0.419
      wheel_radius: 0.09
      
    # Controller configuration
    controllers:
      update_rate: 50
      diff_drive:
        left_wheel_names: ["left_wheel_joint"]
        right_wheel_names: ["right_wheel_joint"]
        publish_rate: 50.0
        
    # Topic remappings
    remappings:
      - from: "/cmd_vel"
        to: "/rt1/cmd_vel"
      - from: "/odom"
        to: "/rt1/odom"
      
    # Path configurations
    paths:
      rviz_config: "rt1_visualization.rviz"
      slam_params: "slam_toolbox_params.yaml"
      nav2_params: "nav2_params.yaml"    # Added: Path to Nav2 parameters
      map_dir: "maps"                    # Added: Directory for map files
      default_map: "empty_map.yaml"      # Added: Default map file name

    # Added: Navigation configuration
    navigation:
      default_bt_xml: "navigate_w_replanning_and_recovery.xml"
      global_frame: "map"
      robot_base_frame: "base_link"
      odom_topic: "/rt1/odom"
      cmd_vel_topic: "/rt1/cmd_vel"
      transform_tolerance: 0.2
      max_vel_x: 0.3                     # RT1's max forward velocity
      min_vel_x: -0.3                    # RT1's max reverse velocity
      max_vel_theta: 1.0                 # RT1's max rotational velocity
      min_vel_theta: -1.0                # RT1's min rotational velocity
      robot_radius: 0.21                 # Based on wheel_separation/2
      inflation_radius: 0.3              # Safe distance from obstacles</document_content>