slam_toolbox:
  ros__parameters:
    use_sim_time: false
    map_update_interval: 5.0
    scan_topic: /scan
    odom_frame: odom
    base_frame: base_link
    map_frame: map
    publish_tf_map: true
    publish_pose: true
    # Add or adjust parameters as needed
